### PR TITLE
Add veux

### PR DESCRIPTION
**Pull request by bexstdev**

### CODE REVIEW

**Review by gwolf2u — CHANGES_REQUESTED** [review]
improper configured repos
https://github.com/crdroidandroid/android_device_xiaomi_veux/blob/14.0/crdroid.dependencies#L15
https://github.com/crdroidandroid/android_device_xiaomi_veux/blob/14.0/crdroid.dependencies#L19

**Comment by bexstdev** [comment]
this is a G-cam repo present in crDroid GitHub org
https://github.com/crdroidandroid/android_device_xiaomi_veux/blob/14.0/crdroid.dependencies#L15
and I've removed the other one.

**Comment by bexstdev** [comment]
https://github.com/crdroidandroid/proprietary_vendor_xiaomi_veux-gcam

**Comment by gwolf2u** [comment]
still invalid... 
for the love of God, do test your dependencies file before submitting request for build server

remove device source and remove local_manifests folder and try to bunch veux

**Pull request closed without merging**
