### PR TITLE
Add courbet

### PR DESCRIPTION
**Pull request by Golbinex**
https://github.com/crdroidandroid/android_device_xiaomi_courbet/blob/14.0/crdroid.dependencies

### CODE REVIEW

**Comment by gwolf2u** [comment]
add support for crDroid 10 first

**Review by gwolf2u — CHANGES_REQUESTED** [review]
https://github.com/crdroidandroid/android_device_xiaomi_courbet/blob/14.0/crdroid.dependencies#L3
create branch here
https://github.com/crdroidandroid/android_device_xiaomi_sm6150-common
don't create new repo

remove lineage dependendencies file
https://github.com/crdroidandroid/android_device_xiaomi_sm6150-common-courbet/blob/14.0/lineage.dependencies

invalid repo
https://github.com/crdroidandroid/android_device_xiaomi_courbet/blob/14.0/crdroid.dependencies#L24

**Comment by Golbinex** [comment]
Addressed repo issues and requested official support.

**Comment by gwolf2u** [comment]
remove
https://github.com/crdroidandroid/android_device_xiaomi_sm6150-common/blob/14.0-courbet/lineage.dependencies

use standard crDroid branch naming
https://github.com/crdroidandroid/android_device_xiaomi_courbet/blob/14.0/crdroid.dependencies#L27

**Comment by gwolf2u** [comment]
resubmit when issues are addressed

**Pull request closed without merging**
