### PR TITLE
build_targets: add ice

### PR DESCRIPTION
**Pull request by sx75**
Add Realme 9 Speed Edition to build targets

### CODE REVIEW

**Review by gwolf2u — CHANGES_REQUESTED** [review]
invalid
https://github.com/crdroidandroid/android_device_realme_ice/blob/14.0/crdroid.dependencies#L3

no need to set branch if using default (in this case 14.0)
https://github.com/crdroidandroid/android_device_realme_ice/blob/14.0/crdroid.dependencies#L10

same here
https://github.com/crdroidandroid/android_device_realme_ice/blob/14.0/crdroid.dependencies#L15

**Comment by sx75** [comment]
Updated with changes

**Comment by gwolf2u** [comment]
Please resolve conflicts

**Comment by sx75** [comment]
Resolved

**Comment by gwolf2u** [comment]
remove extra comma
https://github.com/crdroidandroid/android_device_realme_ice/blob/14.0/crdroid.dependencies#L9

**Comment by sx75** [comment]
Extremely sorry, I skipped that part. Now should be good.

**Comment by sx75** [comment]
If anything else needed, let me know. Thank you in advance !

**Review by gwolf2u — APPROVED** [review]

**Pull request merged**
