### PR TITLE
Add veux

### PR DESCRIPTION
**Pull request by bexstdev**

### CODE REVIEW

**Review by gwolf2u — CHANGES_REQUESTED** [review]
invalid crdroid dependencies file
https://github.com/crdroidandroid/build_targets/blob/14.0/README.md#dependencies

**Comment by ThePrateekBhatia** [comment]
changes are done.

**Review by bexstdev — COMMENTED** [review]
changes are done

**Review by gwolf2u — CHANGES_REQUESTED** [review]
Missing missing crdroidandroid from all repo names

don't declare branch if using defaults
https://github.com/crdroidandroid/android_device_xiaomi_veux/blob/14.0/crdroid.dependencies#L5
same here
https://github.com/crdroidandroid/android_device_xiaomi_veux/blob/14.0/crdroid.dependencies#L11
and here
https://github.com/crdroidandroid/android_device_xiaomi_veux/blob/14.0/crdroid.dependencies#L23

don't declare remote if using default
https://github.com/crdroidandroid/android_device_xiaomi_veux/blob/14.0/crdroid.dependencies#L12
and here
https://github.com/crdroidandroid/android_device_xiaomi_veux/blob/14.0/crdroid.dependencies#L24

you sure?
https://github.com/crdroidandroid/android_device_xiaomi_veux/blob/14.0/crdroid.dependencies#L9

use standard branch naming - 14.0
https://github.com/crdroidandroid/android_device_xiaomi_veux/blob/14.0/crdroid.dependencies#L15

**Comment by gwolf2u** [comment]
did you actually try to build with current dependencies?
remove device source and remove local_manifests folder and try to bunch veux
you'll see...

**Review by bexstdev — COMMENTED** [review]
Changes have been done in the crdroid.dependencies, and yes I'm sure with that oneplus kernel beacause my devices uses sm8350 kernel headers.

**Comment by gwolf2u** [comment]
still invalid dependencies file

> did you actually try to build with current dependencies? 
remove device source and remove local_manifests folder and try to bunch veux you'll see...

**Review by bexstdev — COMMENTED** [review]
sorry about that, just fixed the dependencies, please review and merge.

**Pull request closed without merging**
