### PR TITLE
add Samsung galaxy J3 SM-J320H

### PR DESCRIPTION
**Pull request by Yuzuru-Yamazaki**

### CODE REVIEW

**Comment by Yuzuru-Yamazaki** [comment]
please add Samsung Galaxy J3 which has model number SM-J320H

**Comment by gwolf2u** [comment]
doesn't work this way

**Comment by Yuzuru-Yamazaki** [comment]
Do I have to port it myself?

**Comment by gwolf2u** [comment]
We don't have sources for said device and no device maintainer 
Also is not a port, but rather a build from source 
People seem to get to use the word "port" badly 

So tldr, yes, you got to *build* yourself

**Comment by Yuzuru-Yamazaki** [comment]
ok , thanks for the new info

**Pull request closed without merging**
