### PR TITLE
Add violet

### PR DESCRIPTION
**Pull request by kibria5**

### CODE REVIEW

**Review by gwolf2u — CHANGES_REQUESTED** [review]
invalid dependencies file
https://github.com/crdroidandroid/build_targets/blob/14.0/README.md

**Comment by kibria5** [comment]
> invalid dependencies file https://github.com/crdroidandroid/build_targets/blob/14.0/README.md

https://github.com/crdroidandroid/android_device_xiaomi_violet/commit/6c5062b51af235f79424736e82dd8f957c9060d5

**Comment by gwolf2u** [comment]
> > invalid dependencies file https://github.com/crdroidandroid/build_targets/blob/14.0/README.md
> 
> [crdroidandroid/android_device_xiaomi_violet@6c5062b](https://github.com/crdroidandroid/android_device_xiaomi_violet/commit/6c5062b51af235f79424736e82dd8f957c9060d5)

invalid as I said
read readme linked above

**Comment by kibria5** [comment]
> > > invalid dependencies file https://github.com/crdroidandroid/build_targets/blob/14.0/README.md
> > 
> > 
> > [crdroidandroid/android_device_xiaomi_violet@6c5062b](https://github.com/crdroidandroid/android_device_xiaomi_violet/commit/6c5062b51af235f79424736e82dd8f957c9060d5)
> 
> invalid as I said read readme linked above

i have added can u check again

**Comment by gwolf2u** [comment]
still bad
try to remove local manifest and brunch device, you'll see is not working

from the readme

```
[
  {
    "repository": "crdroidandroid/android_device_oem_codename",
    "target_path": "device/oem/codename",
    "branch": "specific branch",
    "remote": "specific from manifest"
  }
]
```

*repository* - Mandatory needed to be tracked from crDroid repo for dt (common) and kernel  
*target_path* - Path where to clone repo  
*branch* - Defaults to branch of **crdroid** remote from [default.xml](https://github.com/crdroidandroid/android) manifest, however can use different one from tracked repo  
*remote* - Defaults to **github** remote from [default.xml](https://github.com/crdroidandroid/android) manifest, however can use different one from remote list  
  
***Note 1***: *Branch* and *remote* should not be set if using default defined values (ex: with *crDroid 10*, branch is default to *14.0* while remote is *github*)  
***Note 2***: As per rules, repos need to be tracked from crDroid or LOS Github or GitLab

**Comment by kibria5** [comment]
> still bad try to remove local manifest and brunch device, you'll see is not working
> 
> from the readme
> 
> ```
> [
>   {
>     "repository": "crdroidandroid/android_device_oem_codename",
>     "target_path": "device/oem/codename",
>     "branch": "specific branch",
>     "remote": "specific from manifest"
>   }
> ]
> ```
> 
> _repository_ - Mandatory needed to be tracked from crDroid repo for dt (common) and kernel _target_path_ - Path where to clone repo _branch_ - Defaults to branch of **crdroid** remote from [default.xml](https://github.com/crdroidandroid/android) manifest, however can use different one from tracked repo _remote_ - Defaults to **github** remote from [default.xml](https://github.com/crdroidandroid/android) manifest, however can use different one from remote list
> 
> _**Note 1**_: _Branch_ and _remote_ should not be set if using default defined values (ex: with _crDroid 10_, branch is default to _14.0_ while remote is _github_) _**Note 2**_: As per rules, repos need to be tracked from crDroid or LOS Github or GitLab

can u give me access to push repo in gitlab

**Comment by gwolf2u** [comment]
please correct dt dependencies and pull request again

**Pull request closed without merging**
