### PR TITLE
Add Stone

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by gwolf2u — CHANGES_REQUESTED** [review]
https://github.com/crdroidandroid/android_device_xiaomi_stone/blob/14.0/crdroid.dependencies#L5
should change this to 14.0
your device is the only one pulling from there

https://github.com/crdroidandroid/android_device_xiaomi_stone/blob/14.0/crdroid.dependencies#L13
no such repo

https://github.com/crdroidandroid/android_device_xiaomi_stone/blob/14.0/crdroid.dependencies#L23
remove branch as defaults to 14.0 anyway

remove lineage dependencies
https://github.com/crdroidandroid/android_device_xiaomi_sm6375-common/blob/14.0-stone/lineage.dependencies

**Comment by ghost** [comment]
https://github.com/crdroidandroid/android_device_xiaomi_stone/blob/14.0/crdroid.dependencies#L5
for this tree branch name is 14.0-stone and I don't have permission to change branch name

**Comment by gwolf2u** [comment]
> https://github.com/crdroidandroid/android_device_xiaomi_stone/blob/14.0/crdroid.dependencies#L5 for this tree branch name is 14.0-stone and I don't have permission to change branch name

changed

**Comment by ghost** [comment]
Changes done! Please check

**Review by gwolf2u — CHANGES_REQUESTED** [review]
should remove default branch - 14.0 is default anyway for crDroid 10
https://github.com/crdroidandroid/android_device_xiaomi_stone/blob/14.0/crdroid.dependencies#L5

no such repo
https://github.com/crdroidandroid/android_device_xiaomi_stone/blob/14.0/crdroid.dependencies#L13

do remove local manifest and try to build locally to see if works
am getting tired correcting

**Review by gwolf2u — APPROVED** [review]

**Pull request merged**
