### PR TITLE
build_targets: add lisa to jenkins

### PR DESCRIPTION
**Pull request by adrian1234a**

### CODE REVIEW

**Review by gwolf2u — CHANGES_REQUESTED** [review]
only crDroid repos or LOS
https://github.com/crdroidandroid/android_device_xiaomi_lisa/blob/13.0/crdroid.dependencies#L20#L23

**Comment by adrian1234a** [comment]
> only crDroid repos or LOS https://github.com/crdroidandroid/android_device_xiaomi_lisa/blob/13.0/crdroid.dependencies#L20#L23

can you sync that to gitlab crdroid page https://gitlab.com/adri16072002/vendor_xiaomi_lisa-firmware

**Review by gwolf2u — CHANGES_REQUESTED** [review]
bad repo name
https://github.com/crdroidandroid/android_device_xiaomi_lisa/blob/13.0/crdroid.dependencies#L20
`android-vendor-xiaomi-lisa-firmware`

**Comment by adrian1234a** [comment]
> bad repo name https://github.com/crdroidandroid/android_device_xiaomi_lisa/blob/13.0/crdroid.dependencies#L20 `android-vendor-xiaomi-lisa-firmware`

Ready

**Review by gwolf2u — APPROVED** [review]

**Pull request merged**
